CREATE TABLE LOGINUSUARIO(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	CORREO VARCHAR(200) NOT NULL UNIQUE,
	PASSWORD VARCHAR(300) NOT NULL UNIQUE,
	NOMBRE VARCHAR(200) NOT NULL,
	ROLE VARCHAR(200) NOT NULL
);